### ISSUE TITLE
Dashboard & Search

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [overdodactyl/Bugzilla-Dark#2]
https://bugzilla.mozilla.org/page.cgi?id=mydashboard.html needs some background fixed - alternative row backgrounds, and column headers on results, flags etc (I removed identifying info, but you can see what I'm talking about)

![mydash](https://user-images.githubusercontent.com/16656956/34461826-17782e5c-ee9a-11e7-9663-0c4a6d5e3f6b.png)

Search results column headers - https://bugzilla.mozilla.org/buglist.cgi?bug_status=__closed__&email1=arthuredelstein%40gmail.com&emailcc1=1&emailtype1=exact&list_id=13947875

![bug-search](https://user-images.githubusercontent.com/16656956/34461827-1c6d5bbc-ee9a-11e7-8722-92d9a74b502e.png)

**Comment by Thorin-II** [comment]
- "you are CC'd On" (and Flag requested etc) = div class="query_heading"
- descriptions under this ("you are in the CC'd list...") = div class="query_description"

^^ bit faint. #d7d7db (grey-30) works fine

**Comment by Thorin-II** [comment]
On search results (can't test on Dashboard yet), when you start clicking on column headers for sorting, you lose all the dark css

**Comment by overdodactyl** [comment]
Thanks Pants!

How's this look for the Dashboard?

![dashboard](https://user-images.githubusercontent.com/33071129/34462988-2aad45b4-ee47-11e7-8932-57762c18af27.png)

>when you start clicking on column headers for sorting, you lose all the dark css

I'm kinda confused as to what Bugzilla's design is doing here...

It appears they change the color of each previous method you used to sort and gradually make the category lighter and lighter?  After clicking a category it gets `th.sorted_1`, after another gets clicked, `th.sorted_2`, then `th.sorted_3` and so on.  

I don't really see a purpose to this, just seems to over complicate things and add a bunch of meaningless coloration...

Am I missing something here?

For now, I've removed all colors but the selected category:

![search](https://user-images.githubusercontent.com/33071129/34463010-d196ced6-ee47-11e7-97bf-079622d2141f.png)

Edit:  I'm dumb, those are probably secondary sorts..so the darker the color the higher priority of the sort method?

**Comment by Thorin-II** [comment]
Its all good now :+1:  Column headers don't lose their "dark side" no matter how many I click
